services:

  db:
    image: postgres:16 
    shm_size: 128mb
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - antworker

  api:
    image: ghcr.io/theanthil/anthil:v1.0.0
    restart: on-failure
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - antworker

  scheduler:
    image: ghcr.io/theanthil/worker:v1.0.0
    restart: on-failure
    env_file: .env
    networks:
      - antworker
    command: python -m antworker.scheduler


  triggerier:
    image: ghcr.io/theanthil/worker:v1.0.0
    restart: on-failure
    env_file: .env
    networks:
      - antworker
    command: python -m antworker.triggerier


volumes:
  postgres_data:

networks:
  antworker: